#!/usr/bin/env python
# encoding: utf-8

DATA_REDIS_HOST = "cluster2"
DATA_REDIS_PORT = 6379
DATA_VIDEO_REVERSE_TFIDF_DB = 4
DATA_VIDEO_SPARSE_TFIDF_DB = 5
DATA_VIDEO_LDA_DB = 6
DATA_USER_REVERSE_TFIDF_DB = 7
DATA_USER_SPARSE_TFIDF_DB = 8
DATA_USER_LDA_DB = 9

#TF-IDF Parameter
T_MAX_DF = 0.06
T_MAX_FEATURES = 5000

#LDA Parameter
L_MAX_DF = 0.06
L_MAX_FEATURES = 3000
L_TOPICS = 40
L_ITERATIONS = 200
